### ISSUE TITLE
basic installation yields "audience mismatch: domain mismatch" error

### ISSUE THREAD

**Issue by jbclements** [mozilla/mod_authnz_persona#34]
There's nothing more irritating than a bug report that just says "it doesn't work," but there's certainly a dose of that in this one.  Perhaps the saving grace is that I've tested it on a fairly canonically basic configuration.

To wit:

1) Spin up a fresh Ubuntu 14.04 VPS. 
2) follow build instructions (all successful)
3) Visit http://<my ip address>/, verify successful apache2 install
4) Add sample code to 000-default.conf (with 1 change: apxs2 places module in /usr/lib/apache2/, so I used a LoadModule that referred to the absolute path)
5) sudo apache2ctl restart
6) Visit page, see persona login, log in successfully, see popup window close
7) See error page with message:
"audience mismatch: domain mismatch
Please sign in to continue.
Sign in with your email"
Sad face.

My conjecture is that browser-id has been updated since July in a way that makes this project out-of-date?

**Comment by djc** [comment]
It still seems to work for me, so that wouldn't be my conjecture!

What host name are you using, anyway? What host name do you think mod_authnz_persona gets from the VirtualHost configuration environment? Have you checked the Apache error log?

**Comment by jbclements** [comment]
Excellent! I'm delighted to hear that it's still working for you; I'm probably doing something stupid. Perhaps we can improve the README...

To answer your questions: Starting from a stock Ubuntu 14.04 installation, I modified /etc/apache2/sites-available/default only by dropping in the specified lines, with the change to the LoadModule mentioned above.  In this case, then, the hostname is * (as in, <VirtualHost *:80>). To see whether this was the problem, I explicitly inserted the Host's IP address (as in, <VirtualHost 96.126.100.188:80>). In both cases, I'm visiting the machine using an explicit IP address in my web browser (that is, http://96.126.100.188).

The error logs are clean, by which I mean:

[Sat Jan 17 00:37:23 2015] [notice] Apache/2.2.22 (Debian) configured -- resuming normal operations
[Sat Jan 17 00:42:52 2015] [notice] SIGHUP received.  Attempting to restart
[Sat Jan 17 00:42:52 2015] [notice] Apache/2.2.22 (Debian) configured -- resuming normal operations
[Sat Jan 17 00:45:44 2015] [notice] SIGHUP received.  Attempting to restart
[Sat Jan 17 00:45:44 2015] [warn] NameVirtualHost *:80 has no VirtualHosts
[Sat Jan 17 00:45:44 2015] [notice] Apache/2.2.22 (Debian) configured -- resuming normal operations

Finally, you ask what host name mod_authnz_persona gets from the VirtualHost environment, and I'm not sure how I would check that, though I could of course stick some debugging printfs into the mod itself, if it came to that; I haven't dug around in the code much, as it appears that most of the interesting stuff is happening in the .js code.

I've left the machine running, in case you're interested in checking it yourself. I'd be delighted to hear of something obvious!

Many thanks in advance.

**Comment by jbclements** [comment]
I should probably just paste my whole configuration:

```sh

LoadModule authnz_persona_module /usr/lib/apache2/modules/mod_authnz_persona.so

<VirtualHost 96.126.100.188:80>
        ServerAdmin webmaster@localhost

        DocumentRoot /var/www
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /var/www/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Order allow,deny
                allow from all
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride None
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
        </Directory>

<Location />
   AuthType Persona
   Require valid-user
   # Or, require users with host/IdP example.com:
   # Require persona-idp example.com
   # Or, require specific users (requires mod_authz_user)
   # Require user user@example.com
</Location>

        ErrorLog ${APACHE_LOG_DIR}/error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by djc** [comment]
If you turn up the debug level (`LogLevel debug`, I think), there should be line like this in the error log:

    Requesting verification with audience %s

Can you check what it says?

In any case, I'm not quite sure about how IP addresses as hostnames would work.

**Comment by jbclements** [comment]
Excellent! Problem solved. I see that in fact the host for the request is coming from the machine's fqdn (/etc/hostname or similar). When I hit the same machine with this address, everything works as expected. 

May I suggest a note in the README? Perhaps something like this (addition marked with >>>):

"If the cookie is not found, the user agent is served an HTML document that presents a Persona login page.

>> Note that the server's hostname (`hostname -f` or equivalent) must match the domain portion of the URL in order for verification to succeed.

Upon successful authentication with Persona, this page will send a request to the server with a Persona assertion in an HTTP header. The module, upon detecting no cookie is present, will look for this header, validate the assertion, and set a short session cookie."

Thanks for your help!

**Comment by djc** [comment]
Great suggestion! I've copied your text verbatim in f66830e.
